services:
  cns-it:
    build: .
    container_name: cns-it
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    env_file:
      - .env
    environment:
      - NODE_ENV=production
